import { Inter ,Lalezar} from "next/font/google";
import NavBar from "@/component/NavBar/NavBar";
import Footer from "@/component/Footer/Footer";
import { Montserrat} from "next/font/google";
import "./globals.css"
import { ThemeProvider } from "@/component/DarkModeToggle/ThemeContext";
const body_font = Montserrat({ subsets: ["latin"],weight:["400"] });
const inter = Inter({ subsets: ["latin"] });
const lalezar = Lalezar({ subsets: ["arabic"],weight:["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={body_font.className}>
   
      <ThemeProvider>
      <div className="containerBody">  
      
      <NavBar/>
     
               {children}
           <footer>
           <Footer/> 
           </footer>
                </div>
      </ThemeProvider>
                </body>
              
               
    </html>
  );
}
